// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminStats = `-- name: GetAdminStats :one
SELECT 
  (SELECT count(*) FROM users) as total_users,
  (SELECT count(*) FROM users WHERE role = 'mp') as active_mps,
  (SELECT count(*) FROM issues) as total_issues
`

type GetAdminStatsRow struct {
	TotalUsers  int64 `json:"total_users"`
	ActiveMps   int64 `json:"active_mps"`
	TotalIssues int64 `json:"total_issues"`
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(&i.TotalUsers, &i.ActiveMps, &i.TotalIssues)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (actor_id, action, target_id)
VALUES ($1, $2, $3)
RETURNING id, actor_id, action, target_id, created_at
`

type InsertAuditLogParams struct {
	ActorID  pgtype.UUID `json:"actor_id"`
	Action   string      `json:"action"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog, arg.ActorID, arg.Action, arg.TargetID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.TargetID,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, name, email, role, constituency, login_suspended, content_hidden, created_at 
FROM users 
ORDER BY created_at DESC
`

type ListAllUsersRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	Constituency   *string            `json:"constituency"`
	LoginSuspended bool               `json:"login_suspended"`
	ContentHidden  bool               `json:"content_hidden"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Constituency,
			&i.LoginSuspended,
			&i.ContentHidden,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.action, a.created_at, 
       u1.name as actor_name, u1.email as actor_email,
       u2.name as target_name, u2.email as target_email
FROM audit_logs a
LEFT JOIN users u1 ON a.actor_id = u1.id
LEFT JOIN users u2 ON a.target_id = u2.id
ORDER BY a.created_at DESC
LIMIT 50
`

type ListAuditLogsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Action      string             `json:"action"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ActorName   *string            `json:"actor_name"`
	ActorEmail  *string            `json:"actor_email"`
	TargetName  *string            `json:"target_name"`
	TargetEmail *string            `json:"target_email"`
}

func (q *Queries) ListAuditLogs(ctx context.Context) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
			&i.TargetName,
			&i.TargetEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserFlags = `-- name: UpdateUserFlags :one
UPDATE users 
SET login_suspended = $2, content_hidden = $3
WHERE id = $1
RETURNING id, name, email, role, constituency, login_suspended, content_hidden, created_at
`

type UpdateUserFlagsParams struct {
	ID             pgtype.UUID `json:"id"`
	LoginSuspended bool        `json:"login_suspended"`
	ContentHidden  bool        `json:"content_hidden"`
}

type UpdateUserFlagsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	Constituency   *string            `json:"constituency"`
	LoginSuspended bool               `json:"login_suspended"`
	ContentHidden  bool               `json:"content_hidden"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserFlags(ctx context.Context, arg UpdateUserFlagsParams) (UpdateUserFlagsRow, error) {
	row := q.db.QueryRow(ctx, updateUserFlags, arg.ID, arg.LoginSuspended, arg.ContentHidden)
	var i UpdateUserFlagsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Constituency,
		&i.LoginSuspended,
		&i.ContentHidden,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users 
SET role = $2
WHERE id = $1
RETURNING id, name, email, role, constituency, login_suspended, content_hidden, created_at
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

type UpdateUserRoleRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	Constituency   *string            `json:"constituency"`
	LoginSuspended bool               `json:"login_suspended"`
	ContentHidden  bool               `json:"content_hidden"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Constituency,
		&i.LoginSuspended,
		&i.ContentHidden,
		&i.CreatedAt,
	)
	return i, err
}
