// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (issue_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, issue_id, user_id, content, created_at
`

type CreateCommentParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Content string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.IssueID, arg.UserID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByIssue = `-- name: ListCommentsByIssue :many
SELECT c.id, c.issue_id, c.user_id, c.content, c.created_at, u.name as user_name, u.role as user_role
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.issue_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsByIssueRow struct {
	ID        pgtype.UUID        `json:"id"`
	IssueID   pgtype.UUID        `json:"issue_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  string             `json:"user_name"`
	UserRole  string             `json:"user_role"`
}

func (q *Queries) ListCommentsByIssue(ctx context.Context, issueID pgtype.UUID) ([]ListCommentsByIssueRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByIssueRow
	for rows.Next() {
		var i ListCommentsByIssueRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UserName,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
