// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (user_id, title, description, zone, lat, lng)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, description, status, sector, severity, zone, lat, lng, upvotes, created_at, updated_at
`

type CreateIssueParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Zone        *string     `json:"zone"`
	Lat         *float64    `json:"lat"`
	Lng         *float64    `json:"lng"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Zone,
		arg.Lat,
		arg.Lng,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Sector,
		&i.Severity,
		&i.Zone,
		&i.Lat,
		&i.Lng,
		&i.Upvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT id, user_id, title, description, status, sector, severity, zone, lat, lng, upvotes, created_at, updated_at FROM issues WHERE id = $1
`

func (q *Queries) GetIssue(ctx context.Context, id pgtype.UUID) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssue, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Sector,
		&i.Severity,
		&i.Zone,
		&i.Lat,
		&i.Lng,
		&i.Upvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueWithUpvote = `-- name: GetIssueWithUpvote :one
SELECT i.id, i.user_id, i.title, i.description, i.status, i.sector, i.severity, i.zone, i.lat, i.lng, i.upvotes, i.created_at, i.updated_at, 
       EXISTS(SELECT 1 FROM issue_upvotes iu WHERE iu.issue_id = i.id AND iu.user_id = $2) AS is_upvoted
FROM issues i WHERE i.id = $1
`

type GetIssueWithUpvoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetIssueWithUpvoteRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Sector      *string            `json:"sector"`
	Severity    *string            `json:"severity"`
	Zone        *string            `json:"zone"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	Upvotes     *int32             `json:"upvotes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsUpvoted   bool               `json:"is_upvoted"`
}

func (q *Queries) GetIssueWithUpvote(ctx context.Context, arg GetIssueWithUpvoteParams) (GetIssueWithUpvoteRow, error) {
	row := q.db.QueryRow(ctx, getIssueWithUpvote, arg.ID, arg.UserID)
	var i GetIssueWithUpvoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Sector,
		&i.Severity,
		&i.Zone,
		&i.Lat,
		&i.Lng,
		&i.Upvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUpvoted,
	)
	return i, err
}

const listIssues = `-- name: ListIssues :many
SELECT id, user_id, title, description, status, sector, severity, zone, lat, lng, upvotes, created_at, updated_at FROM issues
WHERE ($3::TEXT IS NULL OR zone = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListIssuesParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Zone   *string `json:"zone"`
}

func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssues, arg.Limit, arg.Offset, arg.Zone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Sector,
			&i.Severity,
			&i.Zone,
			&i.Lat,
			&i.Lng,
			&i.Upvotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesWithUpvote = `-- name: ListIssuesWithUpvote :many
SELECT i.id, i.user_id, i.title, i.description, i.status, i.sector, i.severity, i.zone, i.lat, i.lng, i.upvotes, i.created_at, i.updated_at, 
       EXISTS(SELECT 1 FROM issue_upvotes iu WHERE iu.issue_id = i.id AND iu.user_id = $3) AS is_upvoted
FROM issues i
WHERE ($4::TEXT IS NULL OR i.zone = $4)
ORDER BY i.created_at DESC
LIMIT $1 OFFSET $2
`

type ListIssuesWithUpvoteParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	UserID pgtype.UUID `json:"user_id"`
	Zone   *string     `json:"zone"`
}

type ListIssuesWithUpvoteRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Sector      *string            `json:"sector"`
	Severity    *string            `json:"severity"`
	Zone        *string            `json:"zone"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	Upvotes     *int32             `json:"upvotes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsUpvoted   bool               `json:"is_upvoted"`
}

func (q *Queries) ListIssuesWithUpvote(ctx context.Context, arg ListIssuesWithUpvoteParams) ([]ListIssuesWithUpvoteRow, error) {
	rows, err := q.db.Query(ctx, listIssuesWithUpvote,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Zone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesWithUpvoteRow
	for rows.Next() {
		var i ListIssuesWithUpvoteRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Sector,
			&i.Severity,
			&i.Zone,
			&i.Lat,
			&i.Lng,
			&i.Upvotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsUpvoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleUpvote = `-- name: ToggleUpvote :exec
WITH existing AS (
    SELECT 1 FROM issue_upvotes WHERE issue_upvotes.issue_id = $1 AND issue_upvotes.user_id = $2
),
inserted AS (
    INSERT INTO issue_upvotes (issue_id, user_id)
    SELECT $1, $2
    WHERE NOT EXISTS (SELECT 1 FROM existing)
    RETURNING 1
),
deleted AS (
    DELETE FROM issue_upvotes
    WHERE issue_upvotes.issue_id = $1 AND issue_upvotes.user_id = $2
    AND EXISTS (SELECT 1 FROM existing)
    RETURNING 1
)
UPDATE issues 
SET upvotes = upvotes + (SELECT count(*) FROM inserted) - (SELECT count(*) FROM deleted)
WHERE issues.id = $1
`

type ToggleUpvoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ToggleUpvote(ctx context.Context, arg ToggleUpvoteParams) error {
	_, err := q.db.Exec(ctx, toggleUpvote, arg.ID, arg.UserID)
	return err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :exec
UPDATE issues
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateIssueStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error {
	_, err := q.db.Exec(ctx, updateIssueStatus, arg.ID, arg.Status)
	return err
}

const upvoteIssue = `-- name: UpvoteIssue :exec
UPDATE issues
SET upvotes = upvotes + 1
WHERE id = $1
`

func (q *Queries) UpvoteIssue(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, upvoteIssue, id)
	return err
}
