// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDistrictBySlug = `-- name: GetDistrictBySlug :one
SELECT id, name, slug, region_id, created_at FROM districts WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetDistrictBySlug(ctx context.Context, slug string) (District, error) {
	row := q.db.QueryRow(ctx, getDistrictBySlug, slug)
	var i District
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.RegionID,
		&i.CreatedAt,
	)
	return i, err
}

const getRegionBySlug = `-- name: GetRegionBySlug :one
SELECT id, name, slug, capital, created_at FROM regions WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetRegionBySlug(ctx context.Context, slug string) (Region, error) {
	row := q.db.QueryRow(ctx, getRegionBySlug, slug)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Capital,
		&i.CreatedAt,
	)
	return i, err
}

const insertConstituency = `-- name: InsertConstituency :one
INSERT INTO constituencies (name, slug, district_id) VALUES ($1, $2, $3) RETURNING id, name, slug
`

type InsertConstituencyParams struct {
	Name       string      `json:"name"`
	Slug       string      `json:"slug"`
	DistrictID pgtype.UUID `json:"district_id"`
}

type InsertConstituencyRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) InsertConstituency(ctx context.Context, arg InsertConstituencyParams) (InsertConstituencyRow, error) {
	row := q.db.QueryRow(ctx, insertConstituency, arg.Name, arg.Slug, arg.DistrictID)
	var i InsertConstituencyRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const insertDistrict = `-- name: InsertDistrict :one
INSERT INTO districts (name, slug, region_id) VALUES ($1, $2, $3) RETURNING id, name, slug
`

type InsertDistrictParams struct {
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	RegionID pgtype.UUID `json:"region_id"`
}

type InsertDistrictRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) InsertDistrict(ctx context.Context, arg InsertDistrictParams) (InsertDistrictRow, error) {
	row := q.db.QueryRow(ctx, insertDistrict, arg.Name, arg.Slug, arg.RegionID)
	var i InsertDistrictRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const insertRegion = `-- name: InsertRegion :one
INSERT INTO regions (name, slug, capital) VALUES ($1, $2, $3) RETURNING id, name, slug
`

type InsertRegionParams struct {
	Name    string `json:"name"`
	Slug    string `json:"slug"`
	Capital string `json:"capital"`
}

type InsertRegionRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) InsertRegion(ctx context.Context, arg InsertRegionParams) (InsertRegionRow, error) {
	row := q.db.QueryRow(ctx, insertRegion, arg.Name, arg.Slug, arg.Capital)
	var i InsertRegionRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const listConstituenciesByDistrict = `-- name: ListConstituenciesByDistrict :many
SELECT id, name, slug, district_id FROM constituencies WHERE district_id = $1 ORDER BY name ASC
`

type ListConstituenciesByDistrictRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Slug       string      `json:"slug"`
	DistrictID pgtype.UUID `json:"district_id"`
}

func (q *Queries) ListConstituenciesByDistrict(ctx context.Context, districtID pgtype.UUID) ([]ListConstituenciesByDistrictRow, error) {
	rows, err := q.db.Query(ctx, listConstituenciesByDistrict, districtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConstituenciesByDistrictRow
	for rows.Next() {
		var i ListConstituenciesByDistrictRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DistrictID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictsByRegion = `-- name: ListDistrictsByRegion :many
SELECT id, name, slug, region_id FROM districts WHERE region_id = $1 ORDER BY name ASC
`

type ListDistrictsByRegionRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	RegionID pgtype.UUID `json:"region_id"`
}

func (q *Queries) ListDistrictsByRegion(ctx context.Context, regionID pgtype.UUID) ([]ListDistrictsByRegionRow, error) {
	rows, err := q.db.Query(ctx, listDistrictsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistrictsByRegionRow
	for rows.Next() {
		var i ListDistrictsByRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.RegionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many
SELECT id, name, slug, capital FROM regions ORDER BY name ASC
`

type ListRegionsRow struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
	Capital string      `json:"capital"`
}

func (q *Queries) ListRegions(ctx context.Context) ([]ListRegionsRow, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegionsRow
	for rows.Next() {
		var i ListRegionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Capital,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
