// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Action    string             `json:"action"`
	TargetID  pgtype.UUID        `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Briefing struct {
	ID          pgtype.UUID        `json:"id"`
	MpID        pgtype.UUID        `json:"mp_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Zone        *string            `json:"zone"`
	PostType    string             `json:"post_type"`
	Sectors     []string           `json:"sectors"`
	Pinned      bool               `json:"pinned"`
	Views       int32              `json:"views"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	IssueID   pgtype.UUID        `json:"issue_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Constituency struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	DistrictID pgtype.UUID        `json:"district_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type District struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	RegionID  pgtype.UUID        `json:"region_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Sector      *string            `json:"sector"`
	Severity    *string            `json:"severity"`
	Assignee    *string            `json:"assignee"`
	InternalNotes *string          `json:"internal_notes"`
	Zone        *string            `json:"zone"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	Upvotes     *int32             `json:"upvotes"`
	ImageUrls   []string           `json:"image_urls"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IssueUpvote struct {
	IssueID   pgtype.UUID        `json:"issue_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MpProfile struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Party      string             `json:"party"`
	TermStart  string             `json:"term_start"`
	TermEnd    string             `json:"term_end"`
	Bio        string             `json:"bio"`
	Phone      string             `json:"phone"`
	OfficeAddr string             `json:"office_addr"`
	PhotoUrl   string             `json:"photo_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Region struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Capital   string             `json:"capital"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	Role           string             `json:"role"`
	Constituency   *string            `json:"constituency"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LoginSuspended bool               `json:"login_suspended"`
	ContentHidden  bool               `json:"content_hidden"`
}
