// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Briefing struct {
	ID          pgtype.UUID        `json:"id"`
	MpID        pgtype.UUID        `json:"mp_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Zone        *string            `json:"zone"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	IssueID   pgtype.UUID        `json:"issue_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Sector      *string            `json:"sector"`
	Severity    *string            `json:"severity"`
	Zone        *string            `json:"zone"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	Upvotes     *int32             `json:"upvotes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IssueUpvote struct {
	IssueID   pgtype.UUID        `json:"issue_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Constituency *string            `json:"constituency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
