// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetIssue(ctx context.Context, id pgtype.UUID) (Issue, error)
	GetIssueWithUpvote(ctx context.Context, arg GetIssueWithUpvoteParams) (GetIssueWithUpvoteRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListCommentsByIssue(ctx context.Context, issueID pgtype.UUID) ([]ListCommentsByIssueRow, error)
	ListIssues(ctx context.Context, arg ListIssuesParams) ([]Issue, error)
	ListIssuesWithUpvote(ctx context.Context, arg ListIssuesWithUpvoteParams) ([]ListIssuesWithUpvoteRow, error)
	ToggleUpvote(ctx context.Context, arg ToggleUpvoteParams) error
	UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error
	UpvoteIssue(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
