// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error)
	CreateMPProfile(ctx context.Context, arg CreateMPProfileParams) (MpProfile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAdminStats(ctx context.Context) (GetAdminStatsRow, error)
	GetDistrictBySlug(ctx context.Context, slug string) (District, error)
	GetIssue(ctx context.Context, id pgtype.UUID) (Issue, error)
	GetIssueWithUpvote(ctx context.Context, arg GetIssueWithUpvoteParams) (GetIssueWithUpvoteRow, error)
	GetRegionBySlug(ctx context.Context, slug string) (Region, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertConstituency(ctx context.Context, arg InsertConstituencyParams) (InsertConstituencyRow, error)
	InsertDistrict(ctx context.Context, arg InsertDistrictParams) (InsertDistrictRow, error)
	InsertRegion(ctx context.Context, arg InsertRegionParams) (InsertRegionRow, error)
	ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error)
	ListAuditLogs(ctx context.Context) ([]ListAuditLogsRow, error)
	ListCommentsByIssue(ctx context.Context, issueID pgtype.UUID) ([]ListCommentsByIssueRow, error)
	ListConstituenciesByDistrict(ctx context.Context, districtID pgtype.UUID) ([]ListConstituenciesByDistrictRow, error)
	ListDistrictsByRegion(ctx context.Context, regionID pgtype.UUID) ([]ListDistrictsByRegionRow, error)
	ListIssues(ctx context.Context, arg ListIssuesParams) ([]Issue, error)
	ListIssuesWithUpvote(ctx context.Context, arg ListIssuesWithUpvoteParams) ([]ListIssuesWithUpvoteRow, error)
	ListRegions(ctx context.Context) ([]ListRegionsRow, error)
	ToggleUpvote(ctx context.Context, arg ToggleUpvoteParams) error
	UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error
	UpdateUserFlags(ctx context.Context, arg UpdateUserFlagsParams) (UpdateUserFlagsRow, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error)
	UpvoteIssue(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
