// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMPProfile = `-- name: CreateMPProfile :one
INSERT INTO mp_profiles (user_id, party, term_start, term_end, bio, phone, office_addr, photo_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, party, term_start, term_end, bio, phone, office_addr, photo_url, created_at, updated_at
`

type CreateMPProfileParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Party      string      `json:"party"`
	TermStart  string      `json:"term_start"`
	TermEnd    string      `json:"term_end"`
	Bio        string      `json:"bio"`
	Phone      string      `json:"phone"`
	OfficeAddr string      `json:"office_addr"`
	PhotoUrl   string      `json:"photo_url"`
}

func (q *Queries) CreateMPProfile(ctx context.Context, arg CreateMPProfileParams) (MpProfile, error) {
	row := q.db.QueryRow(ctx, createMPProfile,
		arg.UserID,
		arg.Party,
		arg.TermStart,
		arg.TermEnd,
		arg.Bio,
		arg.Phone,
		arg.OfficeAddr,
		arg.PhotoUrl,
	)
	var i MpProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Party,
		&i.TermStart,
		&i.TermEnd,
		&i.Bio,
		&i.Phone,
		&i.OfficeAddr,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role, constituency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, password_hash, role, constituency, created_at, login_suspended, content_hidden
`

type CreateUserParams struct {
	Name         string  `json:"name"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Role         string  `json:"role"`
	Constituency *string `json:"constituency"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Constituency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Constituency,
		&i.CreatedAt,
		&i.LoginSuspended,
		&i.ContentHidden,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, constituency, created_at, login_suspended, content_hidden FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Constituency,
		&i.CreatedAt,
		&i.LoginSuspended,
		&i.ContentHidden,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, role, constituency, created_at, login_suspended, content_hidden FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Constituency,
		&i.CreatedAt,
		&i.LoginSuspended,
		&i.ContentHidden,
	)
	return i, err
}
