
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/govlens/govlens-mvp/backend/internal/api"


)

var tests = []testing.InternalTest{

	{"TestResolveRegistrationRoleDefaultsToCitizen", _test.TestResolveRegistrationRoleDefaultsToCitizen},

	{"TestResolveRegistrationRoleRejectsOpenMPRegistration", _test.TestResolveRegistrationRoleRejectsOpenMPRegistration},

	{"TestResolveRegistrationRoleAllowsMPWithInviteCode", _test.TestResolveRegistrationRoleAllowsMPWithInviteCode},

	{"TestResolveRegistrationRoleAllowsMPWhitelistEmail", _test.TestResolveRegistrationRoleAllowsMPWhitelistEmail},

	{"TestNormalizeIssueStatusInput", _test.TestNormalizeIssueStatusInput},

	{"TestValidateIssueStatusChangeForMP", _test.TestValidateIssueStatusChangeForMP},

	{"TestValidateIssueStatusChangeForAdmin", _test.TestValidateIssueStatusChangeForAdmin},

	{"TestValidateIssueVerificationAction", _test.TestValidateIssueVerificationAction},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/govlens/govlens-mvp/backend/internal/api"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

