/**
 * Typed accessor for constituency GPS center coordinates.
 * Generated by: node scripts/geocode-constituencies.js
 *
 * Import this module instead of the raw JSON to get proper TypeScript types.
 */
import rawData from './constituency-centers.json';

export interface ConstituencyCenter {
    lat: number;
    lng: number;
    isFallback?: boolean;
}

const constituencyCenters = rawData as Record<string, ConstituencyCenter>;

/**
 * Look up the center coordinates for a Ghana constituency by name.
 * Returns null if the name is not found.
 */
export function getConstituencyCenter(name: string): ConstituencyCenter | null {
    return constituencyCenters[name] ?? null;
}

export default constituencyCenters;
